name: Black Sheep RC Club
description: Official website of the Black Sheep RC Club, located in Pendleton, SC.
url: http://www.bsrcc.com
permalink: /news/:year/:month/:day/:title/
exclude:
- README.md
- bower.json
- bower_components
- build
- upload
- serve
- deploy.yaml
- gen_photo_small
- gen_photo_yaml
- assets
- htmltopdf
- Procfile
- rmfm
- old
