name: Black Sheep RC Club
description: Official website of the Black Sheep RC Club, located in Pendleton, SC.
url: http://www.bsrcc.com
permalink: /news/:year/:month/:day/:title
exclude:
- README.md
- build
- upload
- gen_photo_small
- gen_photo_yaml
- assets
- sass
- config.rb
- Procfile
- rmfm
- old
