name: Black Sheep RC Club
description: Official website of the Black Sheep RC Club, located in Pendleton, SC.
url: http://www.blacksheeprcclub.com
permalink: /news/:year/:month/:day/:title
exclude:
- README.md
- upload
- gen_photo_small
- gen_photo_yaml
- assets
- sass
- old
