name: Black Sheep RC Club
description: Official website of the Black Sheep RC Club, located in Pendleton, SC.
url: https://www.bsrcc.com
permalink: /news/:year/:month/:day/:title/
exclude:
- Gemfile
- Gemfile.lock
- README.md
- assets
- htmltopdf
- devserver.sh
- netlify.toml
